# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_remove_quotelist_modified_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotelist',
            options={'verbose_name': 'quote', 'verbose_name_plural': 'quotes'},
        ),
        migrations.AlterModelTable(
            name='quotelist',
            table='quote_quotelist',
        ),
    ]
