# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_auto_20180620_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelist',
            name='name',
            field=models.CharField(default=b'\xea\xb4\x80\xeb\xa6\xac\xec\x9e\x90', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotelist',
            name='translated',
            field=models.CharField(default=b'\xec\x9d\xb4\xec\x8a\xb9\xed\x83\x88\xec\xb6\x9c', max_length=150),
        ),
    ]
