# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='info',
            field=models.TextField(blank=True, verbose_name='한줄요약'),
        ),
    ]
