# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_bookmark_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='owner',
        ),
    ]
