# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_remove_bookmark_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='info',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='한줄요약'),
        ),
    ]
