# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_auto_20180911_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='한줄요약'),
        ),
    ]
