# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_auto_20180911_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='slug',
            field=models.CharField(blank=True, max_length=100, verbose_name='한줄요약'),
        ),
    ]
