# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0008_bookmark_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='slug',
            new_name='info',
        ),
    ]
