# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_auto_20180912_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('-modify_date',)},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='수정일'),
        ),
    ]
