# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 07:51
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180612_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
