# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_note_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(verbose_name=b'\xeb\x82\xb4\xec\x9a\xa9'),
        ),
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xec\x83\x9d\xec\x84\xb1\xec\x9d\xbc'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(blank=True, help_text=b'\xea\xb0\x84\xeb\x8b\xa8\xed\x95\x9c \xec\x84\xa4\xeb\xaa\x85.', max_length=100, verbose_name=b'\xec\x84\xa4\xeb\xaa\x85'),
        ),
        migrations.AlterField(
            model_name='note',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xec\x88\x98\xec\xa0\x95\xec\x9d\xbc'),
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text=b'\xec\xa0\x9c\xeb\xaa\xa9 \xeb\x8c\x80\xec\x8b\xa0 \xec\x93\xb0\xec\x9d\xb4\xeb\x8a\x94 \xed\x95\x9c \xeb\x8b\xa8\xec\x96\xb4.', unique=True, verbose_name=b'\xed\x82\xa4\xec\x9b\x8c\xeb\x93\x9c'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=50, verbose_name=b'\xec\xa0\x9c\xeb\xaa\xa9'),
        ),
    ]
