# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-11 15:48
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='태그'),
        ),
    ]
