# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaderboard',
            new_name='Record',
        ),
    ]
