# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180122_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='highscore',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='record',
            name='player',
            field=models.ForeignKey(default='AAA', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
