# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180124_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gametitle',
            field=models.CharField(default='gametitle', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='score',
            field=models.IntegerField(),
        ),
    ]
