# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180124_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
