# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_auto_20180124_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gametitle', models.CharField(default='monte', max_length=20)),
                ('highscore', models.PositiveSmallIntegerField()),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='highscore',
        ),
        migrations.AlterField(
            model_name='record',
            name='gametitle',
            field=models.CharField(default='monte', max_length=20),
        ),
    ]
