# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='subhead',
            field=models.TextField(blank=True, verbose_name='부제'),
        ),
    ]
