# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_subhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='subhead',
            field=models.CharField(blank=True, max_length=50, verbose_name='부제'),
        ),
    ]
