# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-26 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20180727_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='subhead',
        ),
    ]
