# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180612_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name=b'\xeb\x82\xb4\xec\x9a\xa9'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xec\x83\x9d\xec\x84\xb1\xec\x9d\xbc'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xec\x88\x98\xec\xa0\x95\xec\x9d\xbc'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name=b'\xec\xa0\x9c\xeb\xaa\xa9'),
        ),
    ]
